# Generated by Django 5.2.4 on 2025-07-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phonenumber", models.IntegerField(max_length=10)),
                ("email", models.CharField(max_length=100)),
            ],
        ),
    ]
